# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    env_file:
      - .env
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
